# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-14 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='kind',
            field=models.CharField(choices=[('person', 'person'), ('object', 'object'), ('other', 'other')], default='person', max_length=30),
        ),
    ]
