# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-14 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_auto_20171014_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='long',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
