# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-15 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0003_auto_20171014_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='location',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
