# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-21 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0005_auto_20171015_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=255)),
                ('url_image', models.URLField(blank=True, default='', max_length=255)),
                ('url_link', models.URLField(blank=True, default='', max_length=255)),
                ('kind', models.CharField(choices=[('IT-project', 'IT-project'), ('gallery', 'gallery'), ('external-link', 'external-link'), ('folder', 'folder')], default='folder', max_length=30)),
                ('parent', models.CharField(max_length=40)),
                ('order', models.IntegerField(default=1)),
                ('restricted_to', models.CharField(max_length=255)),
            ],
        ),
    ]
