# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-21 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0006_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='parent',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='restricted_to',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
