# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-21 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0007_auto_20171021_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='key',
            field=models.CharField(default=123, max_length=40),
            preserve_default=False,
        ),
    ]
