# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-21 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0008_item_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
