# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-21 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0010_auto_20171021_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='url_extra',
            new_name='url_docs',
        ),
        migrations.AddField(
            model_name='item',
            name='url_info',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='url_restricted',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='url_wiki',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
