# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-21 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0011_auto_20171021_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url_info',
        ),
        migrations.RemoveField(
            model_name='item',
            name='url_restricted',
        ),
        migrations.AddField(
            model_name='item',
            name='url_docs_type',
            field=models.CharField(choices=[('primary', 'primary'), ('info', 'info'), ('docs', 'docs'), ('wiki', 'wiki'), ('restricted', 'restricted'), ('primary', 'primary')], default='docs', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='url_link_type',
            field=models.CharField(choices=[('primary', 'primary'), ('info', 'info'), ('docs', 'docs'), ('wiki', 'wiki'), ('restricted', 'restricted'), ('primary', 'primary')], default='primary', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='url_wiki_type',
            field=models.CharField(choices=[('primary', 'primary'), ('info', 'info'), ('docs', 'docs'), ('wiki', 'wiki'), ('restricted', 'restricted'), ('primary', 'primary')], default='wiki', max_length=10),
        ),
    ]
