# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-21 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0012_auto_20171021_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url_docs_type',
            field=models.CharField(choices=[('default', 'default'), ('primary', 'primary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='url_link_type',
            field=models.CharField(choices=[('default', 'default'), ('primary', 'primary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')], default='primary', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='url_wiki_type',
            field=models.CharField(choices=[('default', 'default'), ('primary', 'primary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')], default='warning', max_length=10),
        ),
    ]
