# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-23 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0013_auto_20171021_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url_docs_label',
            field=models.CharField(choices=[('default', 'default'), ('primary', 'primary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')], default='docs', max_length=15),
        ),
        migrations.AddField(
            model_name='item',
            name='url_link_label',
            field=models.CharField(choices=[('default', 'default'), ('primary', 'primary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')], default='GO!', max_length=15),
        ),
        migrations.AddField(
            model_name='item',
            name='url_wiki_label',
            field=models.CharField(choices=[('default', 'default'), ('primary', 'primary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')], default='wiki', max_length=15),
        ),
    ]
