# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0014_auto_20171023_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('IT-project', 'IT-project'), ('gallery', 'gallery'), ('external-link', 'external-link'), ('folder', 'folder'), ('wiki', 'wiki'), ('docs', 'docs'), ('restricted', 'restricted'), ('other', 'other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='url_docs_label',
            field=models.CharField(default='docs', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='url_link_label',
            field=models.CharField(default='GO!', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='url_wiki_label',
            field=models.CharField(default='wiki', max_length=15),
        ),
    ]
