# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-01 11:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0015_auto_20171024_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='restricted_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='date'),
        ),
    ]
