name: build-deploy-homebase-aws
on:
  push:
    branches:
      - master

jobs:
  build-deploy-homebase:
    runs-on: ubuntu-latest
    steps:
      - name: execute build & deploy procedure on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_AWS_HOST }}
          username: ${{ secrets.MY_AWS_USER }}
          #password: ${{ secrets.MY_PASSWORD }}
          key: ${{ secrets.MY_AWS_KEY }}
          script: |
             cd ~/my_docker/homebase/homebase
             git pull
             docker build -t my_homebase:latest .
             cd $HOME/shared
             docker-compose -p dockernest up -d
