name: build-deploy-homebase
on:
  push:
    branches:
      - master
      - update-2022

jobs:
  build-deploy-homebase:
    runs-on: ubuntu-latest
    steps:
      - name: execute build & deploy procedure on mintbox
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.MY_USERNAME }}
          password: ${{ secrets.MY_PASSWORD }}
          #key: ${{ secrets.MY_PRIVATE_KEY }}
          script: |
             cd ~/my_docker/homebase/homebase
             git pull
             docker build -t my_homebase:latest .
             cd $HOME/shared
             docker-compose -p dockernest up -d
