name: build-deploy-homebase
on:
  push:
    branches:
      - master
      - update-2022

jobs:
  build-deploy-homebase:
    runs-on: ubuntu-latest
    steps:
      - name: execute build & deploy procedure on mintbox
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.MY_USERNAME }}
          password: ${{ secrets.MY_PASSWORD }}
          #key: ${{ secrets.MY_PRIVATE_KEY }}
          script: |
             cd ~/my_docker/homebase/homebase
             git pull
             docker build -t my_homebase:latest .
            
             # tag for nomad, which uses rootful docker, so needs a pull from a repo
             docker tag my_homebase:latest middle-earth:5000/my_homebase:latest
             docker push middle-earth:5000/my_homebase:latest
            
             cd $HOME/shared
             docker stop my_homebase
             docker rm my_homebase
             docker-compose -p dockernest up -d

             # deploy with nomad
             cd $HOME/my_nomad_datacenter/jobs
             nomad stop my_homebase 
             nomad run my_homebase.nomad